### ISSUE TITLE
Convert to utf-8 

### ISSUE THREAD

**Issue by pathumego** [mooniak/Frequency-Counter#4]
We need to convert the UCSC corpus to utf-8 how to do that?

**Comment by paarandika** [comment]
Those files are in utf-16. I can change code to utf-16 or write a converter to convert utf-8 to utf-16. Or I can write code to support both utf-16 and 8. Which is more preferred?

**Comment by pathumego** [comment]
ok so script supports utf-8 right? So I think bettr to write a converter (utf-16 to utf-8)
