### ISSUE TITLE
Feature Request: Pairs and Triplets 

### ISSUE THREAD

**Issue by impallari** [mooniak/Frequency-Counter#6]
Will it be possible to extend this script to be able to count pairs "ab" and triplets "abc" occurrences?
No rush... just and idea

**Comment by pathumego** [comment]
@impallari Yep, @paarandika  will start work on it guess. What do you think about  #5 ?

**Comment by impallari** [comment]
Yes, that! But instead of using a input file for teaching the script what to look for, simply let the script do the magic, automatically detecting bigrams, trigrams, fourgrams, etc... no input file needed.

**Comment by paarandika** [comment]
Done.

**Comment by pathumego** [comment]
@impallari Done :) Thanks @paarandika

**Comment by pathumego** [comment]
Add matra count too

**Comment by impallari** [comment]
Awesome! Thanks!
